-- 코드를 입력하세요
SELECT BOOK_ID,  author.AUTHOR_NAME, DATE_FORMAT(book.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
from book
join AUTHOR on book.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE book.CATEGORY = '경제'
ORDER BY book.PUBLISHED_DATE ASC;;